config/routes.rb
Rails.application.routes.draw do

  root 'home#index'

  resources :jobs, except: [:edit, :update, :destroy]

  match '/feed' => 'jobs#feed',
        :as => :feed,
        :defaults => { format: 'atom' }, via: :get
end

app/models/concerns/sluggable.rb
module Sluggable
  extend ActiveSupport::Concern

  included do
    validates :slug, presence: true, on: :update
    after_save :generate_slug, if: :slug_must_change?

    def to_param
      "#{id}-#{title.parameterize}"
    end
  end

  private

  def slug_must_change?
    slug != to_param
  end

  def generate_slug
    self.slug = to_param
  end
end

app/models/job.rb
class Job < ActiveRecord::Base
  include Sluggable

  validates :title, :description, :email, :company, presence: true
  validates :email, format: { with: /\A[a-z]([\.\-]?\w+)+@[a-z]([\.\-]?\w+){2,}\Z/ }
  validates :website, :url, format: { with: URI.regexp }, allow_blank: true

  default_scope { order(id: :desc) }
  scope :updated_at_desc, -> { order(updated_at: :desc) }

  # enumerator
  enum modality: { presencial: 0, remote: 1, freela: 2, trainee: 3 }
  enum salary: { undefined: 0, intern: 1, junior: 2, medium: 3, senior: 4 }

  def badge
    "#{modality}-badge.png"
  end

  def modality_name
    ['Presencial', 'Remoto', 'Freela', 'Trainee'][Job.modalities[modality]]
  end

  def salary_label
    ['N/A', 'Abaixo de R$3.000', 'R$3.000 - R$6.000', 'R$6.000 - R$9.000', 'Acima de R$9.000'][Job.salaries[salary]]
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/home_controller.rb
class HomeController < ApplicationController

  def index
    @jobs = Job.first(5)
  end

end

app/controllers/jobs_controller.rb
class JobsController < ApplicationController
  def index
    @jobs = Job.page(params[:page]).per(4)
    @jobs.where!('modality = ?', Job.modalities[params[:modality]]) unless params[:modality].blank?

    respond_to do |format|
      format.html
      format.json
    end
  end

  def new
    @job = Job.new
  end

  def create
    @job = Job.new(job_params)

    if @job.save
      redirect_to @job
    else
      render 'new'
    end
  end

  def show
    @job = Job.find(params[:id])
  end

  def feed
    # this will be the name of the feed displayed on the feed reader
    @title = 'Rubyjobs'

    # the news items
    @job =  Job.updated_at_desc

    # this will be our Feed's update timestamp
    @updated = @job.first.updated_at unless
    @job.empty?

    respond_to do |format|
      format.atom { render layout: false }

      # we want the RSS feed to redirect permanently to the ATOM feed
      format.rss { redirect_to feed_path(format: :atom), status: :moved_permanently }
    end
  end

  private

  def job_params
    params.require(:job).permit(
      :title,
      :email,
      :url,
      :company,
      :skills,
      :location,
      :description,
      :modality,
      :website,
      :salary)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper

  def navbar(*menus)
    menus.reduce('') { |a, e| a << menu_html(e) }
  end

  def menu_html(value)
    "<li class='#{'active' if current_page?(value[1])}'>
      #{link_to value[0], value[1]}
    </li>"
  end

  def controller_action
    "#{params[:controller]}-#{params[:action]}"
  end

  def markdown(text)
    render_options = {
      filter_html: true,
      hard_wrap: true,
      link_attributes: { rel: 'nofollow' }
    }
    renderer = Redcarpet::Render::HTML.new(render_options)
    Redcarpet::Markdown.new(renderer).render(text).html_safe
  end
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/jobs_helper.rb
module JobsHelper
  def link_to_twitter(title)
    tag_a = []
    url = CGI.escape(request.url)
    tag_a << %(<a href="https://twitter.com/intent/tweet?)
    tag_a << %(hashtags=RubyJobs&amp;)
    tag_a << %(original_referer=#{url}&amp;)
    tag_a << %(text=Vaga%20para%20#{CGI.escape(title)}&amp;)
    tag_a << %(tw_p=tweetbutton&amp;url=#{url}")
    tag_a << %(class="btn btn-info" target="_blank" >)
    tag_a << %(<i class="fa fa-twitter fa-lg"> </i>  Tweet</a>)
    tag_a.join.html_safe
  end

  def modalities_hash
    {'Presencial' => :presencial, 'Remoto' => :remote, 'Freela' => :freela, 'Trainee' => :trainee}
  end

  def salaries_hash
    {'N/A' => :undefined, 'Abaixo de R$3.000' => :intern, 'R$3.000 - R$6.000' => :junior, 
      'R$6.000 - R$9.000' => :medium, 'Acima de R$9.000' => :senior }
  end
end

app/views/home/index.html.erb
<header id="home">
	<div class="container">
		<%= image_tag "logo-with-banner.png", class: "logo" %>
		<h2>Está precisando de um Rubista?</h2>
		<p> Anuncie sua vaga no RubyJobs e deixe mais de 4000 desenvolvedores saberem da sua vaga. </p>
		<%= link_to "Anuncie uma vaga!", new_job_path, class: "btn btn-ghost"%>
	</div>
</header>


<div class="main-section" id="<%= controller_action %>">
	<div class="container">

		<div class="row">
			<div class="col-xs-12 col-sm-12 col-md-12 col-lg-12">
				<div class="page-header">
					<h1>Vagas recentes</h1>
				</div>
				<table class="jobs-list">
					<% @jobs.each do |job| %>
					<tr class="<%= job.modality %>">
						<%= content_tag :td, image_tag(job.badge), class: "job-badge" %>
						<%= content_tag :td, (link_to (truncate(job.title, :length => 20)), job_path(job)), class: "job-title" %>
						<%= content_tag :td, (truncate(job.company, :length => 20)), class: "job-company" %>
						<%= content_tag :td, (truncate(job.location, :length => 20)), class: "job-location" %>
						<td class="job-date badger-right badger-<%= job.modality %>" data-badger="<%= job.modality_name %>">
              <%= job.created_at.strftime("%d/%m/%Y") %>
            </td>
					</tr>
					<% end %>
				</table>
				<%= link_to "Ver + vagas", :jobs, class: "show-more-jobs" %>
			</div>
		</div>
   	<!--<script async src="//pagead2.googlesyndication.com/pagead/js/adsbygoogle.js"></script>
    <ins class="adsbygoogle"
         style="display:inline-block;width:728px;height:90px"
         data-ad-client="ca-pub-3241477158749799"
         data-ad-slot="6093586062"></ins>
    <script>
      (adsbygoogle = window.adsbygoogle || []).push({});
    </script>-->

	</div>
</div>

app/views/jobs/_form.html.erb
<div class="row">
  <div class="col-xs-12 col-md-10 col-md-offset-1">
    <%= simple_form_for @job, wrapper_mappings: { radio_buttons: :vertical_radio_and_checkboxes } do |f| %>
      <%= f.error_notification %>
      <%= f.input :company %>
      <%= f.input :website, as: :url %>
      <%= f.input :title %>
      <%= f.input :modality, as: :radio_buttons, collection: modalities_hash %>
      <%= f.input :location %>
      <%= f.input :email %>
      <%= f.input :url, as: :url %>
      <%= f.input :skills %>
      <%= f.input :description %>
      <%= f.input :salary, as: :radio_buttons, collection: salaries_hash %>
      <!--
      <%= f.label :description %>
      <div id="description-editor" class="markdown-editor">
        <ul class="nav nav-tabs" data-tabs="tabs">
          <li class="active">
            <a href="#text" data-toggle="tab">Markdown</a>
          </li>
          <li>
            <a href="#preview" data-toggle="tab">Preview</a>
          </li>
        </ul>
        <div class="tab-content">
          <div class="tab-pane active" id="text">
            <%= f.input :description, input_html: { :size => '50x5', 'v-model' => 'description' }, label: false %>
          </div>
          <div class="tab-pane" id="preview">
            <div class="preview" v-html="description | marked"></div>
          </div>
        </div>
      </div>
      -->

      <%= link_to 'Voltar', root_url, :class => 'btn btn-default' %>
      <%= f.button :submit, label: "Salvar", class: "btn btn-brand" %>
    <% end %>
  </div>
</div>

app/views/jobs/index.html.erb
<header id="inner">
  <div class="container">
  </div>
</header>

<div class="main-section" id="<%= controller_action %>" ng-controller="JobsCtrl">
  <div class="container">

    <div class="row">
      <div class="col-xs-12 col-sm-12 col-md-12 col-lg-12">
        <div class="page-header">
          <h1>Confira as vagas que estão esperando por você! </h1>
        </div>

        <div class="row filters">
          <!--<div class="col-xs-12 col-sm-12 col-md-8 col-lg-8">-->
          <div class="col-xs-12 col-sm-12 col-md-12 col-lg-12">
            <div class="form-group">
              <div class="input-group">
                <input type="text" placeholder="Que tipo de trabalho você esta procurando?" ng-model="search" class="form-control">
                <div class="input-group-addon"><i class="glyphicon glyphicon-search"></i></div>
              </div>
            </div>
          </div>
          <!--<div class="col-xs-12 col-sm-12 col-md-4 col-lg-4">
            <div class="form-group">
              <select ng-model="modality" ng-change="filter()" class="form-control">
                <option value=""> Escolha a modalidade </option>
                <option value="remote"> Remoto </option>
                <option value="presencial"> Presencial </option>
                <option value="freela"> Freela </option>
                <option value="trainee"> Trainee </option>
              </select>
            </div>
          </div>-->
        </div>

        <table class="jobs-list">
          <tbody infinite-scroll="loadMore()" infinite-scroll-distance="3">
            <tr class="{{::job.modality}}" ng-repeat="job in jobs | filter:search">
              <td class="job-badge"><img ng-src="{{::job.badge}}"></td>
              <td class="job-title"><a ng-href="{{::job.url}}">{{::job.title}}</a></td>
              <td class="job-company">
                <a ng-href="{{::job.website}}" ng-if="job.website">
                  {{::job.company}}
                </a>
                <span ng-if="!job.website">
                  {{::job.company}}
                </span>
              </td>
              <td class="job-location"> {{::job.location}} </td>
              <td class="job-date badger-right badger-{{::job.modality}}" data-badger="{{job.modality_name}}">
                {{job.posted_at | date}}
              </td>
            </tr>
          </tbody>
        </table>

        <div class="spinner" ng-show="loading">
          <div class="rect1"></div>
          <div class="rect2"></div>
          <div class="rect3"></div>
          <div class="rect4"></div>
          <div class="rect5"></div>
        </div>

      </div>
    </div>

  </div>
</div>

app/views/jobs/new.html.erb
<header id="inner">
</header>

<div class="main-section" id="<%= controller_action %>">
  <div class="container">
    <div class="row">
      <div class="col-xs-12 col-md-10 col-md-offset-1">
        <div class="page-header">
          <h1>Cadastrar Novo Job</h1>
        </div>
      </div>
    </div>
    <%= render 'form' %>
  </div>
</div>

app/views/jobs/show.html.erb
<% content_for :opengraph do %>
  <meta property="og:type" content="article">
  <%= tag("meta", property: "og:title", content: @job.title ) %>
  <%= tag("meta", property: "og:description", content: @job.description ) %>
  <%= tag("meta", property: "og:url", content: job_url(@job) ) %>
  <%= tag("meta", property: "og:image", content: asset_url('logo-for-opengraph.png') ) %>
  <%= tag("meta", property: "og:site_name", content: "Ruby Jobs" ) %>
<% end %>

<header id="inner">
  <div class="container">
  </div>
</header>

<div class="main-section">
  <div class="container">

    <div class="page-header">
      <h1>
        <%= @job.title %>
      </h1>
      <p>
        <%= content_tag :span, class: "job-company" do %>
          <%= link_to_unless @job.website.blank?, @job.company, @job.website %>
        <% end %>
        <%= content_tag :span, "#{@job.location}/#{@job.modality_name}", class: "job-location" %>
        <%= content_tag :span, l(@job.created_at, format: :long), class: "job-date" %>
      </p>
    </div>

    <div class="job-description">
      <%= markdown @job.description %>
    </div>

    <%= content_tag :div do %>
      Salário <%= @job.salary_label %>
    <% end %>

    <%= content_tag :div, class: "well skills" do %>
      <h4> Habilidades </h4>
      <%= @job.skills %>
    <% end if @job.skills.present? %>

    <div class="row do-you-like-it">

      <div class="col-xs-12 col-sm-12 col-md-1 col-lg-1">
        <%= image_tag  "logo.png" %>
      </div>

      <div class="col-xs-12 col-sm-12 col-md-11 col-lg-11">
        <h4> Gostou da vaga? </h4>
        <p>
          <% if @job.url.present? %>
            <%= link_to 'Participe do processo de seleção', @job.url %> e caso seja contratado deixe-nos saber!
          <% else %>
          Entre em contato com o responsável pelo email <%= content_tag :span, @job.email, class: "email" %> e caso seja contratado deixe-nos saber!
          <% end %>
        </p>
      </div>

    </div>

    <%= link_to 'Voltar', root_url, :class => 'btn btn-default' %>
    <%= link_to_twitter @job.title %>

  </div>
</div>

app/views/layouts/_footer.html.erb
<footer>
	<div class="container">
	  <p> Copyright © <%= Time.now.year %> <strong>RubyJobs.me</strong> </p>
	  <div class="links">
	   <%= link_to image_tag("rss_icon.png"), feed_path %>
	   <%= link_to image_tag("github.png"), "https://github.com/matheusml/rubyjobs" %>
	 </div>
	</div>
</footer>

app/views/layouts/_navbar.html.erb
<div id="main-nav" class="navbar navbar-fixed-top">
  <div class="container">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#site-nav">
        <i class="fa fa-bars"></i>
      </button>
      <%= link_to (image_tag "logo.png"), root_path, class: 'navbar-brand' %>
    </div>

    <div id="site-nav" class="navbar-collapse collapse">
      <ul class="nav navbar-nav navbar-right">
       <%= navbar(
        ['Vagas', jobs_path],
        ['Anuncie', new_job_path]
        ).html_safe %>
      </ul>
    </div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html ng-app="rubyJobs">
<head>
  <title>Ruby Jobs | Trabalhos com Ruby</title>
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <%= stylesheet_link_tag    'application', media: 'all'%>
  <%= javascript_include_tag 'application'%>
  <%= csrf_meta_tags %>
  <%= analytics_init if Rails.env.production? %>
  <%= auto_discovery_link_tag :atom, "/feed" %>
  <%= auto_discovery_link_tag :rss, "/feed.rss" %>

  <%= favicon_link_tag 'ruby.png' %>
  <link href="//maxcdn.bootstrapcdn.com/font-awesome/4.2.0/css/font-awesome.min.css" rel="stylesheet">

  <%= yield :opengraph %>

</head>
<body id="<%= controller_action %>">
  <%= render 'layouts/navbar' %>
  <%= yield %>
  <%= render "layouts/footer" %>
</body>
</html>